#!/bin/bash

kubectl get event --watch &

set -ex

kubectl wait helmrelease gatekeeper --for=condition=Ready --timeout=10m
kubectl wait deployment -n gatekeeper-system gatekeeper-controller-manager --for=condition=Available

kubectl get validatingwebhookconfiguration -A -oyaml
