#!/bin/bash

kubectl get event --watch &

set -ex

kubectl wait helmrelease gatekeeper --for=condition=Deployed --timeout=10m
kubectl wait deployment -n gatekeeper-system gatekeeper-controller-manager --for=condition=Available

kubectl run --privileged --image=busybox --restart=Never violating-pod -- sh -c 'sleep infinity'
